<?php
// Napisz program “jakiej jestem narodowości” z użyciem tablic asocjacyjnych. Program
// powinien przyjmować nazwę kraju, a następnie w zawartej w nim tablicy sprawdzić, jak
// nazywa się odpowiednia narodowość - i tę narodowość zwrócić.

ini_set('display_errors', '1');
ini_set('display_startup_errors', '1');
error_reporting(E_ALL);

// https://www.ef.pl/przewodnik-po-angielskim/gramatyka-angielska/narodowosci-w-jezyku-angielskim/
const nationalities = [
    'Afghanistan' => 'Afghan',
    'Algeria' => 'Algerian',
    'Angola' => 'Angolan',
    'Argentina' => 'Argentine',
    'Austria' => 'Austrian',
    'Australia' => 'Australian',
    'Bangladesh' => 'Bangladeshi',
    'Belarus' => 'Belarusian',
    'Belgium' => 'Belgian',
    'Bolivia' => 'Bolivian',
    'Bosnia and Herzegovina' => 'Bosnian/Herzegovinian',
    'Brazil' => 'Brazilian',
    'Britain' => 'British',
    'Bulgaria' => 'Bulgarian',
    'Cambodia' => 'Cambodian',
    'Cameroon' => 'Cameroonian',
    'Canada' => 'Canadian',
    'Central African Republic' => 'Central African',
    'Chad' => 'Chadian',
    'China' => 'Chinese',
    'Colombia' => 'Colombian',
    'Costa Rica' => 'Costa Rican',
    'Croatia' => 'Croatian',
    'the Czech Republic' => 'Czech',
    'Democratic Republic of the Congo' => 'Congolese',
    'Denmark' => 'Danish',
    'Ecuador' => 'Ecuadorian',
    'Egypt' => 'Egyptian',
    'El Salvador' => 'Salvadoran',
    'England' => 'English',
    'Estonia' => 'Estonian',
    'Ethiopia' => 'Ethiopian',
    'Finland' => 'Finnish',
    'France' => 'French',
    'Germany' => 'German',
    'Ghana' => 'Ghanaian',
    'Greece' => 'Greek',
    'Guatemala' => 'Guatemalan',
    'Holland' => 'Dutch',
    'Honduras' => 'Honduran',
    'Hungary' => 'Hungarian',
    'Iceland' => 'Icelandic',
    'India' => 'Indian',
    'Indonesia' => 'Indonesian',
    'Iran' => 'Iranian',
    'Iraq' => 'Iraqi',
    'Ireland' => 'Irish',
    'Israel' => 'Israeli',
    'Italy' => 'Italian',
    'Ivory Coast' => 'Ivorian',
    'Jamaica' => 'Jamaican',
    'Japan' => 'Japanese',
    'Jordan' => 'Jordanian',
    'Kazakhstan' => 'Kazakh',
    'Kenya' => 'Kenyan',
    'Laos' => 'Lao',
    'Latvia' => 'Latvian',
    'Libya' => 'Libyan',
    'Lithuania' => 'Lithuanian',
    'Madagascar' => 'Malagasy',
    'Malaysia' => 'Malaysian',
    'Mali' => 'Malian',
    'Mauritania' => 'Mauritanian',
    'Mexico' => 'Mexican',
    'Morocco' => 'Moroccan',
    'Namibia' => 'Namibian',
    'New Zealand' => 'New Zealand',
    'Nicaragua' => 'Nicaraguan',
    'Niger' => 'Nigerien',
    'Nigeria' => 'Nigerian',
    'Norway' => 'Norwegian',
    'Oman' => 'Omani',
    'Pakistan' => 'Pakistani',
    'Panama' => 'Panamanian',
    'Paraguay' => 'Paraguayan',
    'Peru' => 'Peruvian',
    'The Philippines' => 'Philippine',
    'Poland' => 'Polish',
    'Portugal' => 'Portuguese',
    'Republic of the Congo' => 'Congolese',
    'Romania' => 'Romanian',
    'Russia' => 'Russian',
    'Saudi Arabia' => 'Saudi, Saudi Arabian',
    'Scotland' => 'Scottish',
    'Senegal' => 'Senegalese',
    'Serbia' => 'Serbian',
    'Singapore' => 'Singaporean',
    'Slovakia' => 'Slovak',
    'Somalia' => 'Somalian',
    'South Africa' => 'South African',
    'Spain' => 'Spanish',
    'Sudan' => 'Sudanese',
    'Sweden' => 'Swedish',
    'Switzerland' => 'Swiss',
    'Syria' => 'Syrian',
    'Thailand' => 'Thai',
    'Tunisia' => 'Tunisian',
    'Turkey' => 'Turkish',
    'Turkmenistan' => 'Turkmen',
    'Ukraine' => 'Ukranian',
    'The United Arab Emirates' => 'Emirati',
    'The United States' => 'American',
    'Uruguay' => 'Uruguayan',
    'Vietnam' => 'Vietnamese',
    'Wales' => 'Welsh',
    'Zambia' => 'Zambian',
    'Zimbabwe' => 'Zimbabwean',
];

function WhatWasMyNationality($country): string {
    if (!is_string($country)) throw new Error('Parameter country must be string type!');
    if (!array_key_exists($country, nationalities)) throw new Error('Unknown country!');

    return nationalities[$country];
}

echo WhatWasMyNationality('Poland').'<br>';
echo WhatWasMyNationality('Transnistria').'<br>';